Repository PloggingMate/PloggingMate_Web, pull requests merged in 2021-09, with the labels that each got.

#1 Frontend : 리액트 초기 설정
  Front-End/.gitignore
  Front-End/package.json
  Front-End/public/favicon.ico
  Front-End/public/index.html
  Front-End/public/manifest.json
  Front-End/public/robots.txt
  Front-End/src/App.css
  Front-End/src/App.js
  Front-End/src/App.test.js
  Front-End/src/components/temp.js
  Front-End/src/index.css
  Front-End/src/index.js
  Front-End/src/pages/temp.js
  Front-End/src/redux/configureStore.js
  Front-End/src/redux/modules/temp.js
  Front-End/src/reportWebVitals.js
  Front-End/src/scss/App.scss
  Front-End/src/setupTests.js
  Front-End/src/shared/temp.js
  Front-End/yarn.lock
  frontend/README.md
Labels: Setting

#6 메인페이지 틀 작성 (일부)
  Front-End/package.json
  Front-End/src/App.js
  Front-End/src/components/Footer.js
  Front-End/src/components/Jumbotron.js
  Front-End/src/components/LoginBox.js
  Front-End/src/components/Navbar.js
  Front-End/src/components/temp.js
  Front-End/src/elements/Card.js
  Front-End/src/index.css
  Front-End/src/pages/Home.js
  Front-End/src/pages/PostList.js
  Front-End/src/scss/App.scss
  Front-End/yarn.lock
Labels: Feature

#23 feat : post 페이지 UI, 기능 / 전체적 UI 수정
  Front-End/package.json
  Front-End/src/App.js
  Front-End/src/components/Post.js
  Front-End/src/pages/Login.js
  Front-End/src/pages/PostDetail.js
  Front-End/src/pages/PostList.js
  Front-End/src/pages/SignUp.js
  Front-End/src/redux/modules/post.js
  Front-End/src/redux/modules/user.js
  Front-End/src/scss/App.scss
  Front-End/src/shared/Connect.js
  Front-End/src/shared/temp.js
  Front-End/yarn.lock
Labels: Feature

#32 feat : 미세먼지 API 연동 / 게시물 작성 페이지 UI 완성
  Front-End/package.json
  Front-End/src/App.js
  Front-End/src/components/Dust.js
  Front-End/src/components/Jumbotron.js
  Front-End/src/components/LoginBox.js
  Front-End/src/components/MapContainer.js
  Front-End/src/components/Navbar.js
  Front-End/src/img/slideImg_3.jpg
  Front-End/src/index.js
  Front-End/src/pages/Login.js
  Front-End/src/pages/PageDetail_Module.js
  Front-End/src/pages/PostDetail.js
  Front-End/src/pages/PostList.js
  Front-End/src/pages/PostWrite.js
  Front-End/src/pages/SignUp.js
  Front-End/src/redux/configStore.js
  Front-End/src/redux/modules/img.js
  Front-End/src/redux/modules/user.js
  Front-End/src/shared/Connect.js
  Front-End/yarn.lock
Labels: Feature

#34 feat : 기타 기능 구현, 주소 검색 api 연결
  Front-End/package.json
  Front-End/public/index.html
  Front-End/src/pages/PostWrite.js
  Front-End/src/redux/modules/post.js
  Front-End/src/redux/modules/user.js
  Front-End/yarn.lock
Labels: Feature

#47 feat : 메인 페이지 랭킹창 생성
  Back-End/src/main/resources/application.yml
  Front-End/package-lock.json
  Front-End/package.json
  Front-End/src/components/Dust.js
  Front-End/src/components/Ranking.js
  Front-End/src/pages/Home.js
  Front-End/src/pages/Login.js
  Front-End/src/pages/SignUp.js
  Front-End/yarn.lock
Labels: Feature

#48 feat : 미세먼지 완성
  Back-End/src/main/java/KBChallenge/BackEnd/PloggingMate/post/PostService.java
  Back-End/src/main/java/KBChallenge/BackEnd/PloggingMate/post/dto/PostListRes.java
  Back-End/src/main/java/KBChallenge/BackEnd/PloggingMate/post/entity/Post.java
  Back-End/src/main/resources/application.yml
  Front-End/src/components/Dust.js
  Front-End/src/components/Jumbotron.js
  Front-End/src/components/LoginBox.js
  Front-End/src/components/Ranking.js
  Front-End/src/img/slideImg_1.jpg
  Front-End/src/img/slideImg_2.jpg
  Front-End/src/pages/Home.js
  Front-End/src/redux/modules/post.js
  Front-End/src/scss/Dust.scss
  Front-End/src/scss/LoginBox.scss
Labels: Feature

#50 feat : post API 연동 (미완성) / 기타 버그 수정
  Front-End/src/components/Dust.js
  Front-End/src/components/Jumbotron.js
  Front-End/src/components/Navbar.js
  Front-End/src/components/Post.js
  Front-End/src/components/Ranking.js
  Front-End/src/pages/PostDetail.js
  Front-End/src/pages/PostList.js
  Front-End/src/pages/PostWrite.js
  Front-End/src/pages/SignUp.js
  Front-End/src/redux/configStore.js
  Front-End/src/redux/modules/post.js
Labels: Bug, Feature

#55 feat : post 등록 api 연동 / 랭킹 api 연동
  Front-End/src/components/Ranking.js
  Front-End/src/pages/PostWrite.js
  Front-End/src/redux/modules/post.js
Labels: Feature

#59 feat : 공원 api 연동 / 리덕스 구조 변경
  Front-End/src/pages/PostWrite.js
  Front-End/src/pages/SignUp.js
  Front-End/src/redux/configStore.js
  Front-End/src/redux/modules/park.js
  Front-End/src/redux/modules/post.js
Labels: Feature
